In [104]:
import numpy as np

In [105]:
X = np.mat([[0,3,1],
            [1,3,1],
            [0,1,1],
            [1,1,1]])

b = np.mat([[0.0474],
            [0.2689],
            [-0.7311],
            [-0.2689]])

s0 = np.mat([[0.9526],
            [0.7311],
            [0.7311],
            [0.2689]])

w0 = np.mat([[-2],
             [1],
             [0]])

In [117]:
J1_w0 = -np.dot(X.T,y-s0) + 2* 0.07*(w0)
J1_w0

matrix([[-0.28  ],
        [ 0.1911],
        [ 0.6837]])

In [118]:
omega = [[s0[0]*(1-s0[0]),0,0,0],
         [0,s0[1]*(1-s0[1]),0,0],
         [0,0,s0[2]*(1-s0[2]),0],
         [0,0,0,s0[3]*(1-s0[3])]]

J2_w0 = np.dot(np.dot(X.T,omega),X)
J2_w0 = J2_w0 + 2*0.07
J2_w0

matrix([[0.53318558, 0.92637116, 0.53318558],
        [0.92637116, 2.70889985, 1.25842367],
        [0.53318558, 1.25842367, 0.77493161]])

In [119]:
w1 = w0 - np.linalg.inv(J2_w0).dot(J1_w0)
w1

matrix([[ 2.14609977],
        [ 2.00437732],
        [-5.36598682]])

In [109]:
X[0,:].dot(w1)

matrix([[0.64714514]])

In [120]:
s11 = 1/(1+np.exp(-X[0,:].dot(w1)))
s12 = 1/(1+np.exp(-X[1,:].dot(w1)))
s13 = 1/(1+np.exp(-X[2,:].dot(w1)))
s14 = 1/(1+np.exp(-X[3,:].dot(w1)))

s1 = np.vstack((s11,s12,s13,s14))
s1

matrix([[0.65636684],
        [0.9423097 ],
        [0.03351705],
        [0.22872762]])

In [121]:
y = [[1],
    [1],
    [0],
    [0]]

In [125]:
J1_w1 = -X.T.dot(y-s1) + 2*0.07*w1
J1_w1

matrix([[ 0.47149129],
        [-0.6611129 ],
        [-0.89031695]])

In [126]:
omega = [[s1[0]*(1-s1[0]),0,0,0],
         [0,s1[1]*(1-s1[1]),0,0],
         [0,0,s1[2]*(1-s1[2]),0],
         [0,0,0,s1[3]*(1-s1[3])]]

J2_w1 = np.dot(np.dot(X.T,omega),X)
J2_w1 = J2_w1 + 2*0.07
J2_w1

matrix([[0.37077343, 0.47949769, 0.37077343],
        [0.47949769, 2.86800883, 1.18853958],
        [0.37077343, 1.18853958, 0.62871649]])

In [127]:
w2 = w1 - np.linalg.inv(J2_w1).dot(J1_w1)
w2

matrix([[-16.44705934],
        [ -6.26854777],
        [ 22.65437748]])

In [130]:
np.linalg.inv(J2_w1)

matrix([[ 13.66314247,   4.87034861, -17.26458961],
        [  4.87034861,   3.34595131,  -9.1974546 ],
        [-17.26458961,  -9.1974546 ,  29.1590726 ]])